enum UIError {
	MALFORMED_EXPRESSION,
	MALFORMED_UINODE,
	INVALID_TYPE
}

enum UIErrorDetail {
	MISS_OPEN_PARENTHESES,
	MISS_CLOSE_PARENTHESES,
	INVALID_TOKEN,
	INVALID_VALUE,
	DIVISION_BY_ZERO,
	MALFORMED,
	
	
}